#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Perl-Version
Version  : 1.013
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Perl-Version-1.013.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Perl-Version-1.013.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libperl-version-perl/libperl-version-perl_1.013-2.debian.tar.xz
Summary  : 'Parse and manipulate Perl version strings'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Perl-Version-bin
Requires: perl-Perl-Version-license
Requires: perl-Perl-Version-man
Requires: perl(File::Slurp::Tiny)
BuildRequires : perl(File::Slurp::Tiny)

%description
Perl-Version version 1.012
INSTALLATION
To install this module, run the following commands:

%package bin
Summary: bin components for the perl-Perl-Version package.
Group: Binaries
Requires: perl-Perl-Version-license
Requires: perl-Perl-Version-man

%description bin
bin components for the perl-Perl-Version package.


%package license
Summary: license components for the perl-Perl-Version package.
Group: Default

%description license
license components for the perl-Perl-Version package.


%package man
Summary: man components for the perl-Perl-Version package.
Group: Default

%description man
man components for the perl-Perl-Version package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Perl-Version-1.013
mkdir -p %{_topdir}/BUILD/Perl-Version-1.013/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Perl-Version-1.013/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Perl-Version
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Perl-Version/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Perl/Version.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/perl-reversion

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Perl-Version/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/perl-reversion.1
/usr/share/man/man3/Perl::Version.3
